### ISSUE TITLE
[BUG] Retrofitting old mycroft skill doesnt create a skill folder and deletes requirements.txt

### ISSUE THREAD

**Issue by LordIvanhoe** [mikejgray/ovos-skill-projen#16] opened 2024-01-16 23:01 UTC
### Description

Trying to retrofit mycroft skill, running **projen new ovosskill --from "@mikejgray/ovos-skill-projen" --retrofit** creates needed folders and files, including requirements.txt
Then, after modifying .projenrc.json and running **npx projen**, it deletes requirements.txt and does not create skill folder at all. No errors are reported.
Output from npx projen:
```
vocab folder not found in original skill; skipping.
dialog folder not found in original skill; skipping.
regex folder not found in original skill; skipping.
intents folder not found in original skill; skipping.
```

### Steps to Reproduce

create a folder and put __init__.py with your skill in it.
inside the folder, run **projen new ovosskill --from "@mikejgray/ovos-skill-projen" --retrofit**
edit .projenrc.json
run **npx projen**

### Other Notes

my skill doesnt have localization folders, but i've tried it with the folders too, same result. even if there are folders, projen says no folders, skipping.

**Comment by LordIvanhoe** [comment] 2024-01-16 23:14
Weird thing i just realised, if i run **npx projen** again, it will recreate requirements.txt. Then if i run it AGAIN, it will delete it again. And so on and so forth.

**Comment by mikejgray** [comment] 2024-01-17 05:40
So I'm seeing two distinct bugs here:

- requirements.txt popping in and out of existence (fixed now)
- localization folders are not read

The retrofit flag doesn't have support for old Mycroft skills that had the code in a subdirectory because my understanding is that wasn't supported. Can you tell me more about that use case? If it's something that is somewhat common I'm happy to open a feature request and add support.

Also, would you please share a tree output? Do each of your folders have `en-us` as a subfolder?

**Comment by LordIvanhoe** [comment] 2024-01-17 19:22
> So I'm seeing two distinct bugs here:
> 
> * requirements.txt popping in and out of existence (fixed now)
> * localization folders are not read

Plus it doesnt actually create the skill folder.

> The retrofit flag doesn't have support for old Mycroft skills that had the code in a subdirectory because my understanding is that wasn't supported. Can you tell me more about that use case? If it's something that is somewhat common I'm happy to open a feature request and add support.

I dont think many people had code inside subfolders, i dont think that would be necessary.

> Also, would you please share a tree output? Do each of your folders have `en-us` as a subfolder?

Here is a fresh test, step by step:
INITIAL FOLDER STRUCT:
![initial](https://github.com/mikejgray/ovos-skill-projen/assets/154831523/f26d6c41-d2c3-47c1-a5cd-ba82a6766ba8)

After running **projen new ovosskill --from "@mikejgray/ovos-skill-projen" --retrofit**
![after RETROFIT](https://github.com/mikejgray/ovos-skill-projen/assets/154831523/a7163021-0ce3-434e-9973-1dbe05b8a81c)

After running **npx projen**
![after npx projen](https://github.com/mikejgray/ovos-skill-projen/assets/154831523/1b8feb02-b823-41f2-912c-6c949d2f206c)

And, output from projen that claims that vocab folder doesnt exist.
![output from projen](https://github.com/mikejgray/ovos-skill-projen/assets/154831523/57dee9ba-e067-4d0b-91d9-1541f65e729b)

As you can see, in the end, it deleted requirements.txt, and did not create the skill subfolder.

**Comment by mikejgray** [comment] 2024-01-21 14:48
Not creating the skill folder is intentional - while it is a Python best practice to put the code inside its own folder, it's complex enough that automating it didn't make sense. There are many ways people set up their original Mycroft skills and I don't think I can account for all of them. If you want to move it to a separate folder, do that part manually and add the `packageDir` variable to your `.projenrc.json` file, then run `npx projen`.

As for the rest, it looks like you're still running an old version of the code. You should be able to clear the package manager cache:

```sh
npm cache clean --force
yarn cache clean
```

And try again, so it will pull the latest version this time.

To confirm, did you add the following to your ~/.npmrc file? Create one if it doesn't exist.

`@mikejgray:registry=https://npm.pkg.github.com`

**Comment by mikejgray** [comment] 2024-01-21 15:39
I spoke with @LordIvanhoe directly on Matrix and worked through some issues loading the latest version of this package. Added the outcome to the README.md file to avoid issues like this in future. Once we've confirmed the new code does what he expects, we can close this issue.

**Closed as completed** 2024-01-23 05:09 UTC
Labels: bug
